export const visualAssets = [
    { id: 1, name: "Fragmented Cityscape", creatorStudio: "Studio Eclipse", description: "Ruined cyberpunk city skyline under a green aurora.", fileSizeMB: 3.2, fileType: "image/png", dimensions: "3840x2160" },
    { id: 2, name: "Memory Stream", creatorStudio: "DreamLab", description: "Abstract river of holographic memories flowing across desert.", fileSizeMB: 2.9, fileType: "image/jpg", dimensions: "1920x1080" },
    { id: 3, name: "Silent Archives", creatorStudio: "LucidFrame", description: "Abandoned archive chambers lit by faint neon strips.", fileSizeMB: 4.1, fileType: "image/png", dimensions: "2560x1440" },
    { id: 4, name: "Cracked Reality Portal", creatorStudio: "Oblivion Works", description: "Glitching portal floating above an abandoned temple.", fileSizeMB: 3.7, fileType: "image/png", dimensions: "3840x2160" },
    { id: 5, name: "Synth Jungle", creatorStudio: "EchoVisual", description: "Overgrown jungle with synthetic plants and neon fauna.", fileSizeMB: 5.0, fileType: "image/jpg", dimensions: "4096x2304" },
    { id: 6, name: "Neural Blossom", creatorStudio: "BioSynth Labs", description: "Fluorescent organic trees wired into neural hubs.", fileSizeMB: 2.5, fileType: "image/png", dimensions: "1920x1200" },
    { id: 7, name: "Temporal Monolith", creatorStudio: "ChronoForge", description: "Massive monoliths emitting time distortion fields.", fileSizeMB: 3.0, fileType: "image/jpg", dimensions: "2560x1600" },
    { id: 8, name: "Lost Market", creatorStudio: "Archive & Sons", description: "Ghostly remnants of a floating bazaar.", fileSizeMB: 2.2, fileType: "image/jpg", dimensions: "1920x1080" },
    { id: 9, name: "Glitch Plains", creatorStudio: "GlitchVerse", description: "Rolling fields intermittently flickering between seasons.", fileSizeMB: 4.6, fileType: "image/png", dimensions: "3440x1440" },
    { id: 10, name: "Augmented Mirage", creatorStudio: "PixelDrift", description: "Oasis generated by malfunctioning reality engines.", fileSizeMB: 3.9, fileType: "image/jpg", dimensions: "3840x2160" },
    { id: 11, name: "Cognitive Spire", creatorStudio: "MindField Studios", description: "Tower constructed from shifting thought constructs.", fileSizeMB: 5.2, fileType: "image/png", dimensions: "4096x4096" },
    { id: 12, name: "Memory Vault Interior", creatorStudio: "NeuroTech", description: "High-security vault storing fragmented dreams.", fileSizeMB: 4.8, fileType: "image/jpg", dimensions: "2880x1800" },
    { id: 13, name: "Subliminal Skyline", creatorStudio: "EchoFrame", description: "Metropolis skyline half-obscured by data fog.", fileSizeMB: 3.3, fileType: "image/png", dimensions: "3840x1600" },
    { id: 14, name: "Forgotten Theatre", creatorStudio: "PastForward", description: "Decaying opera house hosting echoes of forgotten performances.", fileSizeMB: 2.7, fileType: "image/jpg", dimensions: "1920x1080" },
    { id: 15, name: "Synthetic Orchard", creatorStudio: "VitalBloom", description: "Artificial orchard with glass fruit glowing internally.", fileSizeMB: 2.5, fileType: "image/png", dimensions: "2560x1440" }
  ];

  export const musicAssets = [
    { id: 1, name: "Waves of Recall", creatorStudio: "SoundCrafters", description: "Ambient layers representing ripples through memory streams.", bpm: 80, atmosphere: "Calm, Reflective", genre: "Ambient" },
    { id: 2, name: "Neon Pulse", creatorStudio: "Neon Audio", description: "Synthwave bass beats simulating synthetic heartbeats.", bpm: 118, atmosphere: "Energetic, Futuristic", genre: "Synthwave" },
    { id: 3, name: "Data Rain", creatorStudio: "PixelSounds", description: "Slow glitch-hop under atmospheric rainfall.", bpm: 95, atmosphere: "Moody, Slow", genre: "Glitch-Hop" },
    { id: 4, name: "Lament of Forgotten Days", creatorStudio: "ChronoMusic", description: "Orchestral-electronic hybrid mourning lost timelines.", bpm: 72, atmosphere: "Melancholic, Epic", genre: "Dystopian Orchestral" },
    { id: 5, name: "Echo Archives", creatorStudio: "GhostNoise", description: "Ethereal choirs blend with retro-futuristic synth.", bpm: 85, atmosphere: "Haunting, Spiritual", genre: "Ambient Electronic" },
    { id: 6, name: "Glitch Bloom", creatorStudio: "CircuitGarden", description: "Bright glitch melodies unfolding into chaotic crescendos.", bpm: 110, atmosphere: "Chaotic, Bright", genre: "Glitch" },
    { id: 7, name: "Resonant Shards", creatorStudio: "Resonance Labs", description: "Deep resonant drones layered with fractured beats.", bpm: 92, atmosphere: "Mysterious, Dark", genre: "Experimental" },
    { id: 8, name: "Synthetic Dreamscape", creatorStudio: "NeuroPulse", description: "Smooth progressive ambient transitioning into lucid beats.", bpm: 100, atmosphere: "Dreamy, Expansive", genre: "Ambient Chill" }
  ];
  